# Generated by Django 5.1 on 2024-08-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=50)),
                ('cook_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField()),
                ('Recipie', models.TextField()),
                ('dish_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipie', to='dish.dish')),
            ],
        ),
    ]
